[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT"
